namespace Nancy.Bootstrappers.Mef
{

    public interface INancyGeneratedPartMetadata
    {

        /// <summary>
        /// Gets whether or not the export was auto generated.
        /// </summary>
        bool AutoGenerated { get; }

    }

}
